
---
- name: Install Apache, MySQL, and PHP packages
  remote_user: ling
  hosts: all
  become: true
  become_user: root
  gather_facts: true

- name: Include Apache
  import_playbook: apache.yaml

- name: Include MySQL
  import_playbook: mysql.yaml

